"""
밸런스게임 질문 뱅크. 카테고리는 다르지만 '질문형/밸런스게임'이라는
하나의 포맷 정체성 안에서만 소재를 다양화한다.

말투는 음슴체로 통일 (한국 스레드 특유의 반말+음슴체 톤).
각 setup은 2줄: 1줄=상황을 던지는 미니 서사, 2줄=두 선택지를 vs로 제시.

반복 방지 로직상 최근 (전체 개수-1)일 동안 안 겹치므로, 하루 1개씩 발행 기준
한 달(최대 31일) 안에 반복이 안 생기려면 최소 31개가 필요하다. 여유를 둬서 36개로 구성.
"""

QUESTIONS = [
    # 직장생활
    {"id": "job_01", "category": "직장생활",
     "setup": "입사 3년차 되니까 팀장이 은근슬쩍 선택지를 던졌음.\n진급은 미루고 연봉 500 올리거나, 연봉은 그대로에 진급만 확정해준다고 함.",
     "option_a": "연봉 500 UP", "option_a_sub": "진급은 다음에",
     "option_b": "진급 확정", "option_b_sub": "연봉은 동결"},
    {"id": "job_02", "category": "직장생활",
     "setup": "친한 동기가 이직 고민 상담을 해왔음.\n재택 가능한데 승진 느린 회사 vs 매일 출근인데 승진 빠른 회사, 뭐가 나을지 궁금함.",
     "option_a": "재택 가능", "option_a_sub": "승진은 느림",
     "option_b": "매일 출근", "option_b_sub": "승진 빠름"},
    {"id": "job_03", "category": "직장생활",
     "setup": "워라밸이냐 연봉이냐, 회사 고를 때마다 늘 고민되는 부분임.\n야근 없고 칼퇴 보장되는 회사 vs 야근 많은 대신 성과급 두둑한 회사.",
     "option_a": "칼퇴 보장", "option_a_sub": "성과급 없음",
     "option_b": "야근 많음", "option_b_sub": "성과급 두둑"},
    {"id": "job_04", "category": "직장생활",
     "setup": "적성 살려서 박봉으로 사는 삶, 재미없어도 고액연봉으로 사는 삶.\n이 둘 중에 하나만 골라야 한다면 뭐 고를지 진짜 궁금함.",
     "option_a": "좋아하는 일", "option_a_sub": "박봉",
     "option_b": "재미없는 일", "option_b_sub": "고액연봉"},
    {"id": "job_05", "category": "직장생활",
     "setup": "상사는 못 고른다지만 상상은 자유임.\n무능한데 편한 상사 vs 유능한데 진짜 빡센 상사, 어느 쪽이 나을지.",
     "option_a": "무능한 상사", "option_a_sub": "일은 편함",
     "option_b": "유능한 상사", "option_b_sub": "많이 배우지만 빡셈"},
    {"id": "job_06", "category": "직장생활",
     "setup": "회식 문화 얘기만 나오면 회사마다 다 갈림.\n한 달에 한 번 무조건 회식 vs 회식 아예 없는 대신 회식비 현금 지급.",
     "option_a": "월 1회 회식", "option_a_sub": "팀워크는 다짐",
     "option_b": "회식 없음", "option_b_sub": "회식비 현금 지급"},
    {"id": "job_07", "category": "직장생활",
     "setup": "일 잘한다는 소문나면 은근 딜레마 생김.\n인정받는 만큼 일 몰리는 에이스 포지션 vs 티는 안 나도 워라밸 챙기는 무난 포지션.",
     "option_a": "에이스 포지션", "option_a_sub": "일이 계속 몰림",
     "option_b": "무난 포지션", "option_b_sub": "워라밸은 챙김"},
    {"id": "job_08", "category": "직장생활",
     "setup": "점심시간 보내는 스타일도 사람마다 은근 다름.\n1시간 칼같이 챙겨 먹는 사람 vs 짧게 먹고 그만큼 일찍 퇴근하는 사람.",
     "option_a": "점심 1시간", "option_a_sub": "퇴근은 정시",
     "option_b": "점심은 짧게", "option_b_sub": "퇴근은 일찍"},
    {"id": "job_09", "category": "직장생활",
     "setup": "면접 붙고 나면 한 번쯤 하게 되는 고민임.\n연봉은 아쉬운데 워라밸 좋은 회사 vs 연봉은 만족스러운데 야근 잦은 회사.",
     "option_a": "연봉 아쉬움", "option_a_sub": "워라밸 좋음",
     "option_b": "연봉 만족", "option_b_sub": "야근 잦음"},

    # 연애
    {"id": "love_01", "category": "연애",
     "setup": "스레드에서 다들 어떻게 생각하는지 궁금해서 올려봄.\n이상형인데 3개월 만에 헤어질 사람 vs 그냥 그런데 편하게 오래갈 사람.",
     "option_a": "이상형", "option_a_sub": "3개월 컷",
     "option_b": "그냥 그런 사람", "option_b_sub": "평생 편함"},
    {"id": "love_02", "category": "연애",
     "setup": "연애할 때 한 번쯤 다 겪는 고민이라고 생각함.\n나를 엄청 좋아해주는 사람 vs 내가 엄청 좋아하는 사람.",
     "option_a": "날 더 좋아함", "option_a_sub": "내 마음은 반반",
     "option_b": "내가 더 좋아함", "option_b_sub": "상대 마음은 반반"},
    {"id": "love_03", "category": "연애",
     "setup": "연애 오래 하다 보면 결국 다들 부딪히는 문제임.\n초반 설렘이 계속 유지되는 관계 vs 설렘은 없어도 편안한 오래된 관계.",
     "option_a": "계속 설렘", "option_a_sub": "가끔 불안정",
     "option_b": "편안함", "option_b_sub": "설렘은 없음"},
    {"id": "love_04", "category": "연애",
     "setup": "외모냐 성격이냐, 뻔한 주제인데 의외로 은근 갈림.\n잘생겼는데 성격 별로인 사람 vs 평범한데 성격 진짜 좋은 사람.",
     "option_a": "외모 최고", "option_a_sub": "성격은 별로",
     "option_b": "평범한 외모", "option_b_sub": "성격 최고"},
    {"id": "love_05", "category": "연애",
     "setup": "장거리 연애 해본 사람이라면 다 공감할 밸런스게임임.\n장거리 3년 하고 결혼까지 가는 거 vs 그냥 지금부터 쭉 솔로로 지내는 거.",
     "option_a": "장거리 3년", "option_a_sub": "결국 결혼",
     "option_b": "쭉 솔로", "option_b_sub": "마음은 편함"},
    {"id": "love_06", "category": "연애",
     "setup": "결혼 준비하다 보면 한 번쯤 싸우게 되는 주제임.\n빚 좀 내서라도 화려한 결혼식 vs 대출 없이 소박한 결혼식.",
     "option_a": "화려한 결혼식", "option_a_sub": "빚은 좀 생김",
     "option_b": "소박한 결혼식", "option_b_sub": "대출 없음"},
    {"id": "love_07", "category": "연애",
     "setup": "헤어진 뒤 태도로 사람 성향이 은근 갈림.\n전 애인이랑 친구로 지내는 사람 vs 헤어지면 무조건 손절하는 사람.",
     "option_a": "친구로 지냄", "option_a_sub": "가끔 애매함",
     "option_b": "무조건 손절", "option_b_sub": "깔끔하지만 아쉬움"},
    {"id": "love_08", "category": "연애",
     "setup": "기념일 챙기는 스타일도 커플마다 다 다름.\n기념일 하나하나 다 챙기는 사람 vs 기념일 신경 안 쓰는 게 편한 사람.",
     "option_a": "다 챙김", "option_a_sub": "이벤트는 피곤함",
     "option_b": "안 챙김", "option_b_sub": "편하지만 서운할 수도"},
    {"id": "love_09", "category": "연애",
     "setup": "연락 빈도로 커플 스타일이 은근 갈림.\n하루종일 연락해야 안심되는 사람 vs 뜸하다가 만나면 더 애틋한 사람.",
     "option_a": "연락 자주", "option_a_sub": "안정감 있음",
     "option_b": "연락 뜸함", "option_b_sub": "만나면 더 반가움"},

    # 자기계발·라이프스타일
    {"id": "life_01", "category": "라이프스타일",
     "setup": "자기계발 좀 해본 사람이면 다 아는 그 고민임.\n억지로라도 아침형 인간 되기 vs 밤에 집중 잘되는 패턴 그대로 유지하기.",
     "option_a": "아침형 전환", "option_a_sub": "적응 힘듦",
     "option_b": "야행성 유지", "option_b_sub": "아침이 늘 힘듦"},
    {"id": "life_02", "category": "라이프스타일",
     "setup": "헬스 좀 해본 사람이라면 공감할 밸런스게임임.\n운동은 매일 하고 식단은 자유롭게 vs 운동은 안 해도 식단만 철저하게.",
     "option_a": "매일 운동", "option_a_sub": "식단은 자유",
     "option_b": "운동 안 함", "option_b_sub": "식단만 철저"},
    {"id": "life_03", "category": "라이프스타일",
     "setup": "돈 모으는 방식도 사람마다 다 다름.\n아끼면서 여행 자주 가는 스타일 vs 크게 모아서 한 번에 가는 스타일.",
     "option_a": "자주 소소하게", "option_a_sub": "여행 퀄리티는 낮음",
     "option_b": "가끔 크게", "option_b_sub": "기다리는 시간 김"},
    {"id": "life_04", "category": "라이프스타일",
     "setup": "정리 좀 해본 사람이라면 갈리는 주제임.\n물건 최소한만 남기는 미니멀리즘 vs 좋아하는 건 다 쌓아두는 맥시멀리즘.",
     "option_a": "미니멀", "option_a_sub": "청소는 편함",
     "option_b": "맥시멀", "option_b_sub": "볼 때마다 행복"},
    {"id": "life_05", "category": "라이프스타일",
     "setup": "계획형이냐 즉흥형이냐, 성격이 은근 여기서 갈림.\n하루 일정 다 짜놓고 움직이는 사람 vs 그때그때 즉흥적으로 움직이는 사람.",
     "option_a": "계획형", "option_a_sub": "안정적이지만 뻔함",
     "option_b": "즉흥형", "option_b_sub": "재밌지만 피곤함"},
    {"id": "life_06", "category": "라이프스타일",
     "setup": "어디서 살지 한 번쯤 고민해본 사람이라면 공감함.\n조용한 시골에서 여유롭게 사는 삶 vs 바쁜 도시에서 치열하게 사는 삶.",
     "option_a": "시골살이", "option_a_sub": "여유롭지만 심심함",
     "option_b": "도시살이", "option_b_sub": "바쁘지만 활기참"},
    {"id": "life_07", "category": "라이프스타일",
     "setup": "여행 스타일로 사람 성향이 진짜 갈림.\n혼자 자유롭게 다니는 여행 vs 누군가랑 같이 다녀야 재밌는 여행.",
     "option_a": "혼자 여행", "option_a_sub": "자유롭지만 심심할 때 있음",
     "option_b": "같이 여행", "option_b_sub": "재밌지만 맞춰야 함"},
    {"id": "life_08", "category": "라이프스타일",
     "setup": "취미에 돈 쓰는 스타일도 사람마다 다 다름.\n취미엔 돈 아낌없이 쓰는 사람 vs 취미도 가성비 따지는 사람.",
     "option_a": "아낌없이 씀", "option_a_sub": "통장은 얇아짐",
     "option_b": "가성비 따짐", "option_b_sub": "만족도는 낮을 때도"},
    {"id": "life_09", "category": "라이프스타일",
     "setup": "밥집 고르는 스타일도 은근 다들 갈림.\n새로운 곳 계속 찾아다니는 사람 vs 늘 가던 단골집만 가는 사람.",
     "option_a": "새로운 곳", "option_a_sub": "가끔 실패함",
     "option_b": "단골집만", "option_b_sub": "실패는 없지만 뻔함"},

    # 가벼운 취향
    {"id": "taste_01", "category": "가벼운취향",
     "setup": "이거로 은근 싸우는 사람 진짜 많다고 생각함.\n민트초코 좋아하는 민초파 vs 이해가 안 가는 반민초파.",
     "option_a": "민초파", "option_a_sub": "치약맛 좋아함",
     "option_b": "반민초파", "option_b_sub": "이해가 안 감"},
    {"id": "taste_02", "category": "가벼운취향",
     "setup": "계절 취향은 진짜 안 바뀌는 것 같음.\n더워도 여름이 좋은 사람 vs 추워도 겨울이 좋은 사람.",
     "option_a": "여름파", "option_a_sub": "더위는 참을만함",
     "option_b": "겨울파", "option_b_sub": "추위는 참을만함"},
    {"id": "taste_03", "category": "가벼운취향",
     "setup": "여행지 고를 때 한 번쯤 하게 되는 고민임.\n산이 좋은 사람 vs 바다가 좋은 사람.",
     "option_a": "산파", "option_a_sub": "등산은 힘들어도 좋음",
     "option_b": "바다파", "option_b_sub": "물놀이가 최고"},
    {"id": "taste_04", "category": "가벼운취향",
     "setup": "커피 없이 못 사는 사람들 특징이 있다고 생각함.\n아침에 무조건 커피 한 잔 마셔야 하는 사람 vs 오후 되면 커피 없인 못 버티는 사람.",
     "option_a": "아침 커피파", "option_a_sub": "하루 시작 필수",
     "option_b": "오후 커피파", "option_b_sub": "졸릴 때 필수"},
    {"id": "taste_05", "category": "가벼운취향",
     "setup": "여행 스타일도 사람마다 은근 다름.\n익숙한 국내여행 자주 가는 사람 vs 낯선 해외여행 가끔 가는 사람.",
     "option_a": "국내여행파", "option_a_sub": "자주 가는 대신 익숙함",
     "option_b": "해외여행파", "option_b_sub": "가끔이지만 새로움"},
    {"id": "taste_06", "category": "가벼운취향",
     "setup": "주말 보내는 방식으로 성향이 확실히 갈림.\n집이 제일 편한 집순이·집돌이 vs 나가야 힘이 나는 밖순이·밖돌이.",
     "option_a": "집순이·집돌이", "option_a_sub": "집이 제일 편함",
     "option_b": "밖순이·밖돌이", "option_b_sub": "나가야 충전됨"},
    {"id": "taste_07", "category": "가벼운취향",
     "setup": "라면 취향으로 은근 갈리는 사람들이 많다고 생각함.\n매콤한 국물 좋아하는 신라면파 vs 깔끔한 국물 좋아하는 진라면파.",
     "option_a": "신라면파", "option_a_sub": "매콤한 게 최고",
     "option_b": "진라면파", "option_b_sub": "깔끔한 국물 최고"},
    {"id": "taste_08", "category": "가벼운취향",
     "setup": "치킨 시킬 때마다 늘 하게 되는 그 고민임.\n바삭한 후라이드파 vs 달콤한 양념파.",
     "option_a": "후라이드파", "option_a_sub": "바삭함이 생명",
     "option_b": "양념파", "option_b_sub": "달콤함이 생명"},
    {"id": "taste_09", "category": "가벼운취향",
     "setup": "노래방 가면 스타일이 확실히 갈림.\n신나는 노래로 텐션 올리는 사람 vs 발라드로 감성 챙기는 사람.",
     "option_a": "신나는 노래", "option_a_sub": "텐션 최고조",
     "option_b": "발라드", "option_b_sub": "감성 충만"},
]
