"""
밸런스게임 질문 뱅크. 카테고리는 다르지만 '질문형/밸런스게임'이라는
하나의 포맷 정체성 안에서만 소재를 다양화한다.
"""

QUESTIONS = [
    {"id": "job_01", "category": "직장생활",
     "setup": "직장 3년차 A씨 앞에 놓인 선택지.\n대리 진급 대신 연봉 500 인상, 아니면 진급하되 연봉은 동결.",
     "option_a": "연봉 500 UP", "option_a_sub": "진급은 다음에",
     "option_b": "진급 확정", "option_b_sub": "연봉은 동결"},
    {"id": "job_02", "category": "직장생활",
     "setup": "이직 제안을 받은 B씨.\n재택 가능하지만 승진은 느린 회사, 매일 출근이지만 승진 빠른 회사.",
     "option_a": "재택 가능", "option_a_sub": "승진은 느림",
     "option_b": "매일 출근", "option_b_sub": "승진 빠름"},
    {"id": "job_03", "category": "직장생활",
     "setup": "워라밸이냐 연봉이냐, 다들 한 번쯤 고민하는 문제.\n야근 없고 칼퇴 보장 회사 vs 야근 많지만 성과급 두둑한 회사.",
     "option_a": "칼퇴 보장", "option_a_sub": "성과급 없음",
     "option_b": "야근 많음", "option_b_sub": "성과급 두둑"},
    {"id": "job_04", "category": "직장생활",
     "setup": "좋아하는 일 하면서 박봉으로 살지, 재미없어도 고액연봉으로 살지.\n둘 중 하나만 골라야 한다면.",
     "option_a": "좋아하는 일", "option_a_sub": "박봉",
     "option_b": "재미없는 일", "option_b_sub": "고액연봉"},
    {"id": "job_05", "category": "직장생활",
     "setup": "상사 운은 못 고른다지만 상상은 해볼 수 있음.\n무능하지만 편한 상사 vs 유능하지만 빡센 상사.",
     "option_a": "무능한 상사", "option_a_sub": "일은 편함",
     "option_b": "유능한 상사", "option_b_sub": "많이 배우지만 빡셈"},
    {"id": "job_06", "category": "직장생활",
     "setup": "회식 문화 관련 밸런스게임.\n한 달에 한 번 무조건 회식 vs 회식 아예 없는 대신 회식비 현금 지급.",
     "option_a": "월 1회 회식", "option_a_sub": "팀워크는 다짐",
     "option_b": "회식 없음", "option_b_sub": "회식비 현금 지급"},
    {"id": "love_01", "category": "연애",
     "setup": "나 궁금한데 스레드에서 다들 이거 어떻게 생각하는지.\n이상형인데 3개월 안에 헤어질 사람, 그냥 그런데 편하게 오래갈 사람.",
     "option_a": "이상형", "option_a_sub": "3개월 컷",
     "option_b": "그냥 그런 사람", "option_b_sub": "평생 편함"},
    {"id": "love_02", "category": "연애",
     "setup": "연애할 때 다들 한 번쯤 겪는 고민.\n나를 엄청 좋아해주는 사람 vs 내가 엄청 좋아하는 사람.",
     "option_a": "날 더 좋아함", "option_a_sub": "내 마음은 반반",
     "option_b": "내가 더 좋아함", "option_b_sub": "상대 마음은 반반"},
    {"id": "love_03", "category": "연애",
     "setup": "연애 오래 하면 다들 겪는 그 문제.\n초반 설렘이 계속 유지되는 관계 vs 설렘은 없지만 편안한 오래된 관계.",
     "option_a": "계속 설렘", "option_a_sub": "가끔 불안정",
     "option_b": "편안함", "option_b_sub": "설렘은 없음"},
    {"id": "love_04", "category": "연애",
     "setup": "외모 vs 성격, 진짜 뻔한데 은근 갈리는 주제.\n잘생겼는데 성격 별로인 사람 vs 평범한데 성격 진짜 좋은 사람.",
     "option_a": "외모 최고", "option_a_sub": "성격은 별로",
     "option_b": "평범한 외모", "option_b_sub": "성격 최고"},
    {"id": "love_05", "category": "연애",
     "setup": "장거리 연애러들 공감할 밸런스게임.\n장거리 연애 3년 하고 결혼 vs 그냥 지금부터 쭉 솔로.",
     "option_a": "장거리 3년", "option_a_sub": "결국 결혼",
     "option_b": "쭉 솔로", "option_b_sub": "마음은 편함"},
    {"id": "love_06", "category": "연애",
     "setup": "결혼 준비하는 사람이라면 한 번쯤 싸우는 주제.\n화려한 결혼식, 빚 좀 내서라도 vs 소박한 결혼식, 대출 없이.",
     "option_a": "화려한 결혼식", "option_a_sub": "빚은 좀 생김",
     "option_b": "소박한 결혼식", "option_b_sub": "대출 없음"},
    {"id": "life_01", "category": "라이프스타일",
     "setup": "자기계발 좀 해본 사람이면 다 아는 그 고민.\n억지로 아침형 인간 되기 vs 밤에 집중 잘되는 패턴 유지하기.",
     "option_a": "아침형 전환", "option_a_sub": "적응 힘듦",
     "option_b": "야행성 유지", "option_b_sub": "아침이 늘 힘듦"},
    {"id": "life_02", "category": "라이프스타일",
     "setup": "헬스 좀 해본 사람이라면 공감할 밸런스게임.\n운동은 매일 하고 식단은 자유 vs 운동은 안 하고 식단만 철저히.",
     "option_a": "매일 운동", "option_a_sub": "식단은 자유",
     "option_b": "운동 안 함", "option_b_sub": "식단만 철저"},
    {"id": "life_03", "category": "라이프스타일",
     "setup": "돈 모으는 방식도 사람마다 다름.\n돈 아끼며 여행 자주 가기 vs 돈 모아서 한 번 크게 가기.",
     "option_a": "자주 소소하게", "option_a_sub": "여행 퀄리티는 낮음",
     "option_b": "가끔 크게", "option_b_sub": "기다리는 시간 김"},
    {"id": "life_04", "category": "라이프스타일",
     "setup": "정리 좀 해본 사람이라면 갈리는 주제.\n물건 최소한만 남기는 미니멀리즘 vs 좋아하는 건 다 쌓아두는 맥시멀리즘.",
     "option_a": "미니멀", "option_a_sub": "청소는 편함",
     "option_b": "맥시멀", "option_b_sub": "볼 때마다 행복"},
    {"id": "life_05", "category": "라이프스타일",
     "setup": "계획형 vs 즉흥형, 은근 성격 갈리는 주제.\n하루 일정 다 짜놓고 움직이기 vs 그때그때 즉흥적으로 움직이기.",
     "option_a": "계획형", "option_a_sub": "안정적이지만 뻔함",
     "option_b": "즉흥형", "option_b_sub": "재밌지만 피곤함"},
    {"id": "life_06", "category": "라이프스타일",
     "setup": "어디서 살 건지 고민해본 사람이라면.\n조용한 시골에서 여유롭게 vs 바쁜 도시에서 치열하게.",
     "option_a": "시골살이", "option_a_sub": "여유롭지만 심심함",
     "option_b": "도시살이", "option_b_sub": "바쁘지만 활기참"},
    {"id": "taste_01", "category": "가벼운취향",
     "setup": "이거로 은근 싸우는 사람 많던데.\n민트초코 좋아하는 사람 vs 반민초.",
     "option_a": "민초파", "option_a_sub": "치약맛 좋아함",
     "option_b": "반민초파", "option_b_sub": "이해가 안 감"},
    {"id": "taste_02", "category": "가벼운취향",
     "setup": "계절 취향은 진짜 안 바뀌는 듯.\n더워도 여름이 좋은 사람 vs 추워도 겨울이 좋은 사람.",
     "option_a": "여름파", "option_a_sub": "더위는 참을만함",
     "option_b": "겨울파", "option_b_sub": "추위는 참을만함"},
    {"id": "taste_03", "category": "가벼운취향",
     "setup": "여행지 고를 때 한 번쯤 하는 고민.\n산이 좋은 사람 vs 바다가 좋은 사람.",
     "option_a": "산파", "option_a_sub": "등산은 힘들어도 좋음",
     "option_b": "바다파", "option_b_sub": "물놀이가 최고"},
    {"id": "taste_04", "category": "가벼운취향",
     "setup": "커피 없이 못 사는 사람들 특징.\n아침에 무조건 커피 한 잔 vs 오후 되면 커피 없인 안 됨.",
     "option_a": "아침 커피파", "option_a_sub": "하루 시작 필수",
     "option_b": "오후 커피파", "option_b_sub": "졸릴 때 필수"},
    {"id": "taste_05", "category": "가벼운취향",
     "setup": "여행 스타일도 사람마다 다름.\n익숙한 국내여행 자주 vs 낯선 해외여행 가끔.",
     "option_a": "국내여행파", "option_a_sub": "자주 가는 대신 익숙함",
     "option_b": "해외여행파", "option_b_sub": "가끔이지만 새로움"},
    {"id": "taste_06", "category": "가벼운취향",
     "setup": "주말 보내는 방식으로 갈리는 성향.\n집에서 쉬는 게 최고인 집순이·집돌이 vs 나가야 힘이 나는 밖순이·밖돌이.",
     "option_a": "집순이·집돌이", "option_a_sub": "집이 제일 편함",
     "option_b": "밖순이·밖돌이", "option_b_sub": "나가야 충전됨"},
]
